name: Vaccine doses administered
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        uses: actions/install-pipenv

      - name: Run
        run: make -f ./vaccine-doses-administered/Makefile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        uses: actions/commit
        if: always()
        with:
            message: vaccines-doses-administered scrape
